"""Create lightweight research figures without optional plotting dependencies."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from research_common import (
    CORE_DEFENSE_CONFIGS,
    DEFAULT_OUTPUT_DIR,
    PROJECT_ROOT,
    load_json,
    run_research_suite_sync,
    write_artifact_bundle,
    write_csv,
    write_json,
)


ARCHITECTURE_MERMAID = """flowchart LR
    A[User / Document Input] --> B[Agent Orchestrator]
    B --> C[SentinelAgent Middleware]
    C --> D[Detectors]
    D --> E[Policy Engine]
    E --> F{Tool Allow / Block}
    F --> G[Metrics Logger]
    D --> G
"""


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate SentinelAgent research figure artifacts.")
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT_DIR)
    parser.add_argument("--refresh", action="store_true", help="Regenerate research benchmark inputs first.")
    return parser.parse_args()


def load_or_refresh(output_dir: Path, refresh: bool) -> dict[str, Any]:
    artifact_path = output_dir / "research_benchmark_results.json"
    if refresh or not artifact_path.exists():
        artifact = run_research_suite_sync(
            defense_configs=CORE_DEFENSE_CONFIGS,
            output_dir=output_dir,
            num_runs=1,
            include_benign=True,
            deterministic_timings=True,
        )
        write_artifact_bundle(
            prefix="research_benchmark",
            output_dir=output_dir,
            artifact=artifact,
            title="SentinelAgent Research Benchmark",
            notes=["Generated by make_research_figures.py --refresh."],
        )
    return load_json(artifact_path)


def bar(value: float, width: int = 28) -> str:
    filled = int(round(max(0.0, min(1.0, value)) * width))
    return "#" * filled + "." * (width - filled)


def figure_markdown(artifact: dict[str, Any]) -> str:
    metrics = artifact.get("metrics", [])
    rows = [
        "# SentinelAgent Research Figures",
        "",
        "## Figure 1. Architecture",
        "",
        "```mermaid",
        ARCHITECTURE_MERMAID.strip(),
        "```",
        "",
        "## Figure 2. Attack Success Rate By Defense",
        "",
        "| Defense | ASR | Bar |",
        "| --- | --- | --- |",
    ]
    for row in metrics:
        asr = float(row.get("attack_success_rate", 0.0))
        rows.append(f"| {row.get('defense_config')} | {asr * 100:.1f}% | `{bar(asr)}` |")

    rows.extend([
        "",
        "## Figure 3. Utility And Latency",
        "",
        "| Defense | Benign Success | Latency ms | Throughput qps |",
        "| --- | --- | --- | --- |",
    ])
    for row in metrics:
        benign = float(row.get("benign_task_success_rate", 0.0))
        rows.append(
            "| {defense} | {benign:.1f}% | {latency:.2f} | {throughput:.3f} |".format(
                defense=row.get("defense_config"),
                benign=benign * 100,
                latency=float(row.get("avg_latency_ms", 0.0)),
                throughput=float(row.get("throughput_qps", 0.0)),
            )
        )
    rows.append("")
    return "\n".join(rows)


def main() -> int:
    args = parse_args()
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    artifact = load_or_refresh(output_dir, args.refresh)

    metrics = artifact.get("metrics", [])
    figure_rows = []
    for row in metrics:
        defense_config = row.get("defense_config")
        figure_rows.extend([
            {
                "figure_id": "attack_success_rate_by_defense",
                "defense_config": defense_config,
                "metric": "attack_success_rate",
                "value": row.get("attack_success_rate"),
            },
            {
                "figure_id": "utility_and_latency",
                "defense_config": defense_config,
                "metric": "benign_task_success_rate",
                "value": row.get("benign_task_success_rate"),
            },
            {
                "figure_id": "utility_and_latency",
                "defense_config": defense_config,
                "metric": "avg_latency_ms",
                "value": row.get("avg_latency_ms"),
            },
            {
                "figure_id": "utility_and_latency",
                "defense_config": defense_config,
                "metric": "throughput_qps",
                "value": row.get("throughput_qps"),
            },
        ])
    paths = {
        "architecture": output_dir / "architecture.mmd",
        "figures_csv": output_dir / "research_figures.csv",
        "figures_md": output_dir / "research_figures.md",
        "figures_json": output_dir / "research_figures.json",
    }
    paths["architecture"].write_text(ARCHITECTURE_MERMAID, encoding="utf-8")
    write_csv(paths["figures_csv"], figure_rows, ["figure_id", "defense_config", "metric", "value"])
    paths["figures_md"].write_text(figure_markdown(artifact), encoding="utf-8")
    write_json(paths["figures_json"], {
        "metadata": {
            "source": "research_benchmark_results.json",
            "api_keys_required": False,
        },
        "figure_data": figure_rows,
        "architecture_mermaid": ARCHITECTURE_MERMAID,
        "attack_success_rate": [
            {
                "defense_config": row.get("defense_config"),
                "attack_success_rate": row.get("attack_success_rate"),
            }
            for row in metrics
        ],
        "utility_latency": [
            {
                "defense_config": row.get("defense_config"),
                "benign_task_success_rate": row.get("benign_task_success_rate"),
                "avg_latency_ms": row.get("avg_latency_ms"),
                "throughput_qps": row.get("throughput_qps"),
            }
            for row in metrics
        ],
    })

    print("Wrote research figure artifacts:")
    for path in paths.values():
        print(f"- {path.resolve().relative_to(PROJECT_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
